### ISSUE TITLE
Yo Haaris, what's cracking and where did you disappear to?

### ISSUE THREAD

**Issue by MohamudMussa** [HaarismoghalQA/HobbyProject#22]

**Comment by HaarismoghalQA** [comment]
I had covid, I was hospitalised for 2 weeks. I had to drop out because I was falling behind but I was allowed to rejoin in may.  Add me on teams we can have a chat : HMoghal@qa.com

**Comment by MohamudMussa** [comment]
left QA brother, so I can't even chat on teams, drop me a message on 07476592066

**Comment by MohamudMussa** [comment]
✅
